//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenizerNet.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TokenizerNet.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # SentenceBreakProperty-12.1.0.txt
        ///# Date: 2019-03-10, 10:53:28 GMT
        ///# © 2019 Unicode®, Inc.
        ///# Unicode and the Unicode Logo are registered trademarks of Unicode, Inc. in the U.S. and other countries.
        ///# For terms of use, see http://www.unicode.org/terms_of_use.html
        ///#
        ///# Unicode Character Database
        ///#   For documentation, see http://www.unicode.org/reports/tr44/
        ///
        ///# ================================================
        ///
        ///# Property:	Sentence_Break
        ///
        ///#  All code points not explicitly listed for Sentence_Break
        ///#  have the  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SentenceBreakProperty {
            get {
                return ResourceManager.GetString("SentenceBreakProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # WordBreakProperty-12.1.0.txt
        ///# Date: 2019-03-10, 10:53:28 GMT
        ///# © 2019 Unicode®, Inc.
        ///# Unicode and the Unicode Logo are registered trademarks of Unicode, Inc. in the U.S. and other countries.
        ///# For terms of use, see http://www.unicode.org/terms_of_use.html
        ///#
        ///# Unicode Character Database
        ///#   For documentation, see http://www.unicode.org/reports/tr44/
        ///
        ///# ================================================
        ///
        ///# Property:	Word_Break
        ///
        ///#  All code points not explicitly listed for Word_Break
        ///#  have the value Other  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WordBreakProperty {
            get {
                return ResourceManager.GetString("WordBreakProperty", resourceCulture);
            }
        }
    }
}
